In [2]:
import numpy as np

In [3]:
#1 Создайте вектор с элементами от 12 до 42
np.linspace(12, 42, 43-12)

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.,
       38., 39., 40., 41., 42.])

In [4]:
#2 Создайте вектор из нулей длины 12, но его пятый елемент должен быть равен 1
x = np.zeros(12)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#3 Создайте матрицу (3, 3), заполненую от 0 до 8
x = np.linspace(0, 8, 9)
x.reshape((3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [6]:
#4 Найдите все положительные числа в np.array([1,2,0,0,4,0])
x = np.array([1,2,0,0,4,0])
x[x > 0]

array([1, 2, 4])

In [7]:
#5 Умножьте матрицу размерности (5, 3) на (3, 2)
x = np.linspace(1, 15, 15)
x = x.reshape((5,3))
y = np.linspace(1, 6, 6)
y = y.reshape((3,2))

np.dot(x, y)

array([[ 22.,  28.],
       [ 49.,  64.],
       [ 76., 100.],
       [103., 136.],
       [130., 172.]])

In [8]:
#6 Создайте матрицу (10, 10) так, чтобы на границе были 0, а внтури 1
x = np.ones(10)
x[0] = 0
x[9] = 0

y = np.tile(x, 10)
y = y.reshape((10,10))
y*np.transpose(y)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
#7 Создайте рандомный вектор и отсортируйте его
x = np.random.random(8)
x.sort()
x

array([0.08982334, 0.20140714, 0.30149921, 0.30396217, 0.60688744,
       0.65573869, 0.75932239, 0.99044529])

In [10]:
#8 Каков эквивалент функции enumerate для numpy массивов?
x = np.array([[1, 2], [3, 4]])
for index, val in np.ndenumerate(x):
    print(index, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [11]:
#9* Создайте рандомный вектор и выполните нормализацию столбцов 
# (из каждого столбца вычесть среднее этого столбца, из каждого столбца вычесть sd этого столбца)

# Непонятная формулировка задачи.

In [12]:
#10* Для заданного числа найдите ближайший к нему элемент в векторе
arr = 10*np.random.random(10)
x = 5

idx = np.abs(arr-x).argmin()

print(idx, arr[idx])
print(arr)

8 3.8851598670358123
[3.08372321 3.16855168 8.68000614 3.3272961  2.5082356  7.33017519
 1.55264086 7.56020992 3.88515987 3.83884612]


In [25]:
#11* Найдите N наибольших значений в векторе
arr = 100*np.random.random(20)
N = 10

np.argsort(arr)[-N:] # получаем индексы наибольших элементов

array([14,  9,  7,  6, 15,  3,  0, 16, 13,  8])