In [2]:
import numpy as np

In [7]:
#1
np.linspace(12, 42, 43-12)

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.,
       25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37.,
       38., 39., 40., 41., 42.])

In [8]:
#2
x = np.zeros(12)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#3
x = np.linspace(0, 8, 9)
x.reshape((3,3))

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [13]:
#4
x = np.array([1,2,0,0,4,0])
x[x > 0]

array([1, 2, 4])

In [18]:
#5
x = np.linspace(1, 15, 15)
x = x.reshape((5,3))
y = np.linspace(1, 6, 6)
y = y.reshape((3,2))

np.dot(x, y)

array([[ 22.,  28.],
       [ 49.,  64.],
       [ 76., 100.],
       [103., 136.],
       [130., 172.]])

In [38]:
x = np.ones(10)
x[0] = 0
x[9] = 0

y = np.tile(x, 10)
y = y.reshape((10,10))
y*np.transpose(y)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
#7
x = np.random.random(8)
x.sort()
x

array([0.07191028, 0.13563962, 0.29225772, 0.39726973, 0.48044105,
       0.75632386, 0.94463613, 0.98918843])

In [24]:
#8
x = np.array([[1, 2], [3, 4]])
for index, val in np.ndenumerate(x):
    print(index, val)


(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
#9 ???

In [40]:
#10
arr = 10*np.random.random(10)
x = 5

idx = np.abs(arr-x).argmin()

print(idx, arr[idx])
print(arr)

9 5.259079060407626
[2.06722803 2.78342805 9.77461541 3.15124564 0.45368418 6.82879034
 0.31297024 0.90131952 7.68011257 5.25907906]


In [ ]:
#11
arr = 100*np.random.random(10)
N = 10
